import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen max-w-full bg-gray-100  ">        
        <header className=" mx-auto">
          <nav className="flex items-center justify-around bg-blue-950 text-white mx-auto p-4">
            <div className="flex font-bold text-gray-50 text-3xl justify-items-end-safe ">Next App</div>
            
            <div className="nav-links space-x-40 text-lg font-semibold font-xl text-gray-50 justify-items">
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/contact">Contact</Link>
            </div>
          </nav>
        </header>

        <main >
          {children}
        </main>

        <footer className="bg-blue-950 text-white text-center p-4">
          <p>&copy; 2026 Next App. All rights reserved.</p>
        </footer>

      </body>
    </html>
  );
}